services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container_name
    environment:
      - PGADMIN_DEFAULT_EMAIL=edwinandrew96@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrics_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/postgres_data
volumes:
  postgres_data: