services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrics_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/postgres_data
volumes:
  postgres_data: